### ISSUE TITLE
Tracking: Add PlaineKevin to admin-wg

### ISSUE THREAD

**Issue by groundwater** [electron/governance#461]
Tracking issue to add @PlaineKevin to admin-wg and governance

- [x] Update Permissions 
  - [x] https://github.com/electron/.permissions/pull/108
- [x] Add to Governance Docs 
  - [x] https://github.com/electron/governance/pull/460
- [x] `@electronjs.org` email
- [x] update slack membership
- [x] Community & Safety Approval

**Comment by ckerr** [comment]
@groundwater is there anything left to be done before this issue can be closed?

**Comment by Sami-ab** [comment]
001380001*
